### ISSUE TITLE
Error: Deployment failed: Error: Environment still has health Yellow 180 seconds after update finished!

### ISSUE THREAD

**Issue by yewon-Noh** [t-world-team/celebring_be#35]
## Error Message

```
Error: Deployment failed: Error: Environment still has health Yellow 180 seconds after update finished!
```

### 원인

- 네트워크 등 여러 가지 이유로 Elastic Beanstalk과의 통신 속도가 느려 문제가 없음에도, 제한 시간 안에 health check를 완료하지 못해 timeout 발생

### 해결 방법

- health check를 하는 시간(`wait_for_environment_recovery`) 을 늘려준다.

```yml
      - name: Deploy Consumer to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: celebring-api
          environment_name: Celebring-api-env
          version_label: github-action-${{steps.current-time.outputs.formattedTime}}
          region: ap-northeast-2
          deployment_package: deploy/deploy.zip
          wait_for_environment_recovery: 300
```
